[package]
name = "aiDot-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thirtyfour = "0.35"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rumqttc = "0.24"
dotenv = "0.15"
chrono = "0.4"
log = "0.4"
